### ISSUE TITLE
Issue with text

### ISSUE THREAD

**Issue by RUNETHERABBITYT** [kwsch/pk3DS#133]
Omg what am i doing i meant to say that please provide a fix for if i screwed up anything or give a way to say like hey backup your game text thing Or just tell me how to do it in VIDEO forme plzzz it's so much easier to understand Thanks

**Comment by sora10pls** [comment]
Translating that to English... he randomized Game Text and Story Text, and wants to revert the changes. I've already provided him with both a reason why and a solution over at GBAtemp.

You can close :)
![img_8200](https://cloud.githubusercontent.com/assets/17801814/25141036/426f1718-2430-11e7-88f4-8703bdface34.PNG)

**Comment by RUNETHERABBITYT** [comment]
Or just provide a game text file so it dosent look like https://gyazo.com/02c965e70c102d032e64bb5197066930

**Comment by RUNETHERABBITYT** [comment]
Link?

**Comment by sora10pls** [comment]
I'm not sharing the GARC with you. Read the solution I gave to you instead of having us share copyrighted data with you...

**Comment by kwsch** [comment]
pk3DS uses the selected language text files to display info instead of hardcoded lists. It allows for multi-language support as well as supporting any user-provided edits.

Since it supports user-provided edits, randomizing the game text files yields what you are experiencing.
You can temporarily restore the gametext garc yourself.
