### ISSUE TITLE
.code.bin is not a  patchable exefs

### ISSUE THREAD

**Issue by ahiddenwaffle** [kwsch/pk3DS#142]
Get this error when trying to rebuild S/M as patch... 

System.Exception:ExeFS\.code.bin is not a patchable ExeFS
(no rom2: found).
 at pk3DS.Patch.B_PatchCIA_click(Object sender, EventArgs
e)

**Comment by kwsch** [comment]
>(no rom2: found).

nobody uses the code patching thing (was just a PoC), hopefully you aren't confusing this with another tool.

**Comment by sora10pls** [comment]
If you'd like a much more reliable method of running mods for SM with a patch, I recommend [SaltySD](https://github.com/shinyquagsire23/SaltySD). It works with all versions of the games (v1.0, v1.1, and v1.2), and just requires you to patch `code.bin` for the desired version (and of course have the corresponding RomFS files on the SD Card at `/saltysd/SunMoon`). Plenty of tutorials on how to get it working.

Also saves the trouble of rebuilding a `.3DS` or `.CIA` (also saves time for installation if `.CIA`) since it's RomFS redirection, akin to LayeredFS (or Riivolution on the Wii if you're familiar with that).

**Comment by ahiddenwaffle** [comment]
What Im trying to do is run the modified game as a patch with luma.... Ill try saltySD like sora10pls mentioned.

**Comment by ahiddenwaffle** [comment]
Solved my issue using luma patching ✅
