### ISSUE TITLE
[Feature Request] Remove Trade Evolution Option

### ISSUE THREAD

**Issue by ReaperJack** [kwsch/pk3DS#168]
Similar to how the universal pokemon randomizer can remove trade evolutions and replace them with another method e.g leveling up, is it possible to do that with PK3DS?

**Comment by sora10pls** [comment]
Since pk3DS isn't just a randomizer, but a ROM editor, you could always just edit the evolution methods to your liking...

What I did to compensate for this was edit the evolution methods to include offline methods for trades (ie for Magmar, use Magmarizer), and then edit Item Stats for Magmarizer to have the same effect as an evolutionary Stone (ie Water Stone, Fire Stone, Ice Stone, etc.)
