### ISSUE TITLE
[Feature Request] Ability to limit randomization to single Types

### ISSUE THREAD

**Issue by Bradyoactiv** [kwsch/pk3DS#203]
I would like to see the ability to randomize Pokemon and have them all be a specific type.

**Comment by kwsch** [comment]
set the Same Type percent to 100

**Comment by sora10pls** [comment]
I think he means for Trainer/Wild editors. Have a drop-down that allows the user to select which one Type will appear in Trainer/Wild battles

**Comment by kwsch** [comment]
I don't feel that it's necessary to implement every possible customization under the sun (complicates things); this sort of mod is easy for a forked version of the program that is compiled just for the purposes described.

In the following file & location:
https://github.com/kwsch/pk3DS/blob/43b629803bd91ff6b6eff5475c1625107afdc2d8/pk3DS.Core/Randomizers/SpeciesRandomizer.cs#L24-L28

Can insert the following:
```c#
list = list.Where(z => SpeciesStat[z].Types.Contains(0)).ToArray();
```
can do different filtering too, so that an approved list of types is available (ie Dragon/Water/Fire/Grass pkm only)
```c#
var approvedTypes = new[] {0,5,7,12}; // arbitrary type IDs
list = list.Where(z => SpeciesStat[z].Types.Any(type => approvedTypes.Contains(type))).ToArray();
```
