### ISSUE TITLE
ORAS Wild Randomizer Not Working 

### ISSUE THREAD

**Issue by JackTheMenace** [kwsch/pk3DS#213]
This Message Came Up When I Was Randomizing Wild Encounters in Pokemon Omega Ruby. Any Help?

Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.RSWE.B_Randomize_Click(Object sender, EventArgs e) in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Subforms\Gen6\RSWE.cs:line 595
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.152, Culture=neutral, PublicKeyToken=null
C:\Users\JackT\Documents\PK3DS\b152\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Jack\Documents\PK3DS\b152\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by sora10pls** [comment]
>C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Subforms\Gen6\RSWE.cs:line 595

Line 595 is just the alert before randomizing, so I figured that couldn't be the reason for the exception. Debugging with VS gave me a better idea of what's broken, since I got [this exception](https://pastebin.com/HjNtYTTw).

After debugging:
![image](https://user-images.githubusercontent.com/17801814/31510721-4e2565f4-af53-11e7-8e80-2abd5525259e.png)

**Comment by jpmac26** [comment]
I'm getting this error as well, and I've tried tracing the problem a bit. The exception occurs because RandomList seems to always be smaller than max.Length. However, I tried setting this code to instead only iterate between 0 and RandomList.Length, and the code instead went into an infinite loop in the ShuffleSlots() method, which leads me to believe the problem is actually originating from something else.

Perhaps we're not initializing RandomList with the proper size? That's about as much as I can guess from a cursory inspection.

**Comment by kwsch** [comment]
Current:
https://github.com/kwsch/pk3DS/blame/c0d9e4b5f705bed36df51cfdd43576bec1ad3645/pk3DS/Subforms/Gen6/RSWE.cs#L645-L648

Previous:
https://github.com/kwsch/pk3DS/blame/12719e0049831c4b01dfd42d5c2c2fbb918b1f55/pk3DS/Subforms/Gen6/RSWE.cs#L626-L629

probably using max instead of RandomList; can probably remove the if check and just populate the randomlist completely.
