### ISSUE TITLE
[USUM Randomised] game freezes during a certain point at 2nd Aether visit

### ISSUE THREAD

**Issue by ishtiaq1234** [kwsch/pk3DS#248]
Whenever i get to the point when you do a multi battle against Faba and An Aether Employee with Hau on the Second Visit to Aether Paradise the game seems to freeze
Faba’s randomised class is Pokemon Trainer (Colress - his vs music from bw plays)
and the Employee uses the pokemon trainer (Kukui) class as well

do i need to change the classing of the one of the characters due to both of them having unique battle themes or something else entirely?

**Comment by sora10pls** [comment]
I can test this when I’m home, I’ve never had this happen to me when I played a Sun randomizer

**Comment by ishtiaq1234** [comment]
should have said dis earlier but it doesnt give a luma error like it does with any other game its just a black screen and colress’s battle music just plays infinitely unless the 3ds is turned off

**Comment by sora10pls** [comment]
Yeah I'm unable to replicate this. Game loads totally fine with no crashes/softlocks, regardless of Trainer order (Kukui first + his battle music, or Colress first + his battle music; latter is what you mentioned).

![1](https://user-images.githubusercontent.com/17801814/33804755-05ccccd4-dd7a-11e7-8b67-ba94a6868800.png)
![2](https://user-images.githubusercontent.com/17801814/33804756-05f83bf8-dd7a-11e7-8d4c-c0d60039c4a3.png)

**Comment by sora10pls** [comment]
I was able to replicate this!

Employee (left) -> Maxie
Employee (right) -> Archie
Hau -> Lusamine (Mother Beast; unused in USUM)

The problem lies with, not your opponents, but your ally. Can you please look into which Trainer Class Hau has for that battle, @ishtiaq1234? His Trainer ID will depend on which starter you chose. Since it's a randomizer, whichever slot.

1st starter (originally Rowlet): `Pokémon Trainer - 200`
2nd starter (originally Litten): `Pokémon Trainer - 201`
3rd starter (originally Popplio): `Pokémon Trainer - 202`

This can easily be fixed by simply adding a blacklisted set of Trainer Classes for USUM, similar to my recent PR for ORAS with leftover XY Trainer Classes.

**Comment by sora10pls** [comment]
Should we find any other Trainer Classes that cause this, they can be added over time. For now, my most recent commit in PR #252 resolves this.

**Comment by ishtiaq1234** [comment]
Yup looks like Hau was randomised into Aether President - 082 changed it back to Hau’s original and it worked now thanks :)

**Comment by EntityMays** [comment]
Hi. I randomly came across this thread when searching "Aether President - 082" on google. I had searched that up because I was wondering if its possible to hack in Mother Beast Lusamine (which is Aether President - 082) in Ultra Sun and Ultra Moon despite not appearing in the game but an option being available in PK3DS. However, by taking a look at what @sora10pls said in this thread, it seems like @ishtiaq1234 s game crashed when that trainer class was used, so...I take it that it's not possible or is just that one instance? Please let me know as I am creating my own sort of game using PKhex. I hope you can help.

**Comment by kwsch** [comment]
If some trainer classes are disallowed for randomization, then they're not usable for manual edits either. Prevented those values from being chosen to prevent freezes.
