### ISSUE TITLE
Static Encounters not having randomized movesets

### ISSUE THREAD

**Issue by uscdude92** [kwsch/pk3DS#298]
Hi, I'm trying to randomize the movesets of the static encounters, by randomizing movesets first, then randomizing the static encounters, yet the movesets remain what they would originally be? Any suggestions?

**Comment by sora10pls** [comment]
I am also able to replicate this, unsure why though since SMTE properly sets the randomized moves back when using the current levelup moves button:
![image](https://user-images.githubusercontent.com/17801814/36942459-f0f3ad2a-1f3f-11e8-9f2b-940a031a745c.png)

https://github.com/kwsch/pk3DS/blob/788958a4f1987291034529d3f78ffaec6bdd0ae6/pk3DS/Subforms/Gen7/StaticEncounterEditor7.cs#L599

**Comment by bryancoene9** [comment]
I'm having the same problem as that guy, but the proof above is showing that trainers are getting randomized. I'm playing usum, and static encounters such as totem trials will be random pokemon, but it will be the standard moveset for them. I've been trying different orders of activation to see if any of them work but it doesn't seem to be doing anything

**Comment by bryancoene9** [comment]
I've played a bit through the hack that I have problems with. The first encounter on route 1 counts as a static encounter. In my case it became a sylveon with cloud nine, but the moves were its normal moveset at the level it was at. I started training it, and the randomization started kicking in. This is telling me that its reading that these Pokemon have their randomized learnsets, but that something with encounters in the static encounters editor is overriding that, which I'd think would be a problem.
