### ISSUE TITLE
gen 7 trainer class bug

### ISSUE THREAD

**Issue by poke-hexedit** [kwsch/pk3DS#330]
if you check "ignore special classes" it doesn't actually block special classes, it still randomizes trainers like lusamine/guzma/etc and other trainers into important trainers

**Comment by sora10pls** [comment]
Able to replicate, Ignore Special Classes was checked and every important Trainer had their class randomized.
![image](https://user-images.githubusercontent.com/17801814/39408871-0e56bf8c-4bab-11e8-9aae-2eaaeb2bf0e2.png)

https://github.com/kwsch/pk3DS/blob/f9d9b8878af210890f324b2dfa9e1cdb442a9034/pk3DS/Subforms/Gen7/SMTE.cs#L628-L640

**Comment by kwsch** [comment]
Seems like moving the `` && CHK_IgnoreSpecialClass.Checked`` to the top and negating (ie !CHK...) would prevent special classes from being shuffled.

The rv == 082 needs to be moved inside the `do` so that it properly randomizes away from the current trainer class rather than skipping the trainer entirely

**Comment by sora10pls** [comment]
Doing so wouldn't randomize *any* trainer classes if the checkbox is checked. Testing right now with:

```
if (CHK_RandomClass.Checked && !CHK_IgnoreSpecialClass.Checked)
   {
     int randClass() => (int)(Util.rnd32() % CB_Trainer_Class.Items.Count);
     int rv; do { rv = randClass(); }
     while (TrainerClasses.Contains(rv) && rv == 082); // don't allow disallowed classes
     tr.TrainerClass = (byte) rv;
   }
```

If checked, no classes get randomized.
If not checked, works as intended.
