### ISSUE TITLE
Changing Evolution Methods 

### ISSUE THREAD

**Issue by MightyBirdy** [kwsch/pk3DS#35]
Is Pangoro's "Level Up with Dark Type in Party" hardcoded specifically as such in the game, or is it possible to change what type like with Sylveon's method? And is "Level Up Female (SetForm 1)" specific to Espurr or would it work with any Pokemon that has an alternate forme?

Similarly, it is possible to inverse the Ninjask/Shedinja situation, so that rather that it gives you two Pokemon from one evolution, using up a space in your party and a PokeBall, is there a way to have one evolution essentially "consume" (delete as opposed to create) a second Pokemon? The only practical use for this would be Slowpoke, so I'm assuming it's not likely.

Also, the notes say 
>                1, // 28 - Dark Type Party
>                6, // 29 - Affection + MoveType
>                1, // 30 - Dark Type
But only one of these is actually a new method. Is 30 meant to be the Inkay method?

**Comment by kwsch** [comment]
Dark Type in party: Yes, the gen6 games only have 3 params:

> method: (level up with dark type in party)
> result species: (pangoro)
> argument: (level=32)

Gen7 is likely different, they Level and Form in addition to the Argument. Check back when that editor is added for G7 📟 

Level Up Female (SetForm 1) -- no it's not hardcoded per Espurr, it only requires a female gender and sets the formID to 1. It's only necessary since Meowstic has different movepools per gender.

Ninjask/Shedinja combining: no, it just triggers a creation of a pkm -- you'd need to modify game code to add a new evolution method to do such a thing.

 1, // 30 - Dark Type
outdated comment, updated in https://github.com/kwsch/pk3DS/commit/8bf57739e696e2499fead10b183003f7f8f5e956
