### ISSUE TITLE
[Enhancement] Move values and flags

### ISSUE THREAD

**Issue by Tyulis** [kwsch/pk3DS#352]
Hello.
Sorry, I cannot really pull request for that because I don't have any knowledge in C# and I don't even have a Windows.
For another project, I tried to look at the bitflags in the US/UM move files. It has already been asked in #323 and #189, so it can be useful here.
First, in US/UM, move data takes 0x27 bytes (not 0x23 like it is apparently written in pk3DS.Core/Structures/Gen6/Move6.cs)
I already found a few interesting flags, I'm not sure at 100%, but this seems to be right.

0x0B: ?
0x1E: Z-move ID (0 for status Z-moves as they are move-specific, their effect is at 0x21)
0x20: Z-move power
0x21: Z-move effect (see below)

0x22: ? (Always 0, 1, 2, 3 or 4)
0x23: ? (Always 0, 25, 50 or 100, maybe a percentage?)

(From left to right, if we can say that)

0x24:

- Punch
- Copiable by Mirror Move
- ?
- Affected by Mirror coat and Mirror Bounce
- Affected by Protect and Detect
- Has a recharging turn after usage
- Has a charging turn before usage
- Contact ?? (absolutely not sure)

0x25:

- ?
- ?
- Passes through substitutes
- Healing move
- Reaches opposite side in triple battle ?
- Defrost when used
- Prevented by gravity
- Sound move

0x26:

- unused
- unused
- unused
- unused
- unused
- unused
- unused
- Dance move

0x27: unused

**Comment by Tyulis** [comment]
Just to anticipate some questions, my theory is that these are just flags for moves, abilities and items effects : for example, I think that the charging turn is implemented in the move effect routine denoted by its ID in another field, and the "charging turn" flag here is just to know which moves activate the power herb.

**Comment by Tyulis** [comment]
I just provided a few informations that can be used in this program, this isn't implemented yet.

First, yes, you can change the identified stuff without touching to this. As far as I know, those flags are used for items, abilities and moves effects - as I said before, this won't change the charging turn, but for example it can change the effect of other things like the soundproof ability.

Then, the effect field is the identifier of the move effect routine - for example, the effect no. 123 is the Frustration effect, which make the power to change depending on the user's happiness. In fact, most of the actual effects depend on this, and not on those flags, which are - I think - only there to identify some types of moves without having to look at there effect.

**Comment by ewormPL** [comment]
Okay, so I've figured out one thing for sure: **Flags correspond to Z-Move effects**

On damaging moves, Flag 2 is always 0, while Flag 1 is equal to the power of the Z-move after transforming. For example, Brick Break will turn into All-Out Pummelling with the power of 140, because it's Flag 1 = 140.

On status moves, the situation is only slightly more complex. Flag 1 will always be 0, while Flag 2 is one of the following numbers indicating given effects:
1 -> +1 Attack
2 -> +2 Attack
3 - > +3 Attack
4 -> +1 Defense
5 -> +2 Defense
6 -> +3 Defense
7 -> +1 Special Attack
8 -> +2 Special Attack
9 -> +3 Special Attack
10 -> +1 Special Defense
11 -> +2 Special Defense
12 -> +3 Special Defense
13 -> +1 Speed
14 -> +2 Speed
15 -> +3 Speed
16 -> +1 Accuracy
17 -> +2 Accuracy
18 -> +3 Accuracy
19 -> +1 Evasiveness
20 -> +2 Evasiveness
21 -> +3 Evasiveness
22 -> +1 to all (except Accuracy or Evasiveness)
23 -> +2 to all (except Accuracy or Evasiveness)
24 -> +3 to all (except Accuracy or Evasiveness)
25 -> raises critical-hit ratio two stages
26 -> resets lowered stats of the user
27 -> recovers all of user's HP
28 -> recovers all Hp of the Pokémon switching-in (Memento and Parting Shot)
29 -> makes the user the center of attention
30 -> only on Curse: recovers all HP if the user's a Ghost type, +1 Attack otherwise

Note that many of these are not attributed to any move in the actual games. I mean, +3 to all stats is nuts.

I will have to see if it's possible to mix Flag 1 and Flag 2, essentially giving a damaging Z-Move an additional effect. So much ridiculously broken attacks just waiting to happen in awful hacks...

and one more thing: **the 0xD field (next to the status infliction chances) determines how long the inflicted status lasts** according to the following:
1 - status is permanent (poison, paralysis, burn, freeze, but also on Ingrain, identification moves like Foresight and some others)
2 - status lasts a set amount of turns (sleep, confusion, but also Perish Song, Heal Block, Telekinesis and some others)
3 - lasts forever unless switched out (currently only on Attract)
4 - lasts a set amount of turns and prevents switching (trapping moves like Fire Spin or Whirlpool)

And finally, in order to make a move to inflict bad poison (like Toxic and Poison Fang), one should choose the standard poison options, but also put 15 in both "TurnMin" and "TurnMax" fields (where normal poison has 0s).

The field "Inflict %" is only for damaging moves.

Now I'm diving into studying the "Effect" field. This one has the most unique values and I hope to find out exactly what they mean and how they work.

**Comment by Tyulis** [comment]
Great job! I hope that @kwsch will take a look someday. 

The `effect` field is the index of the actual effect, for example, 0 for no additional effect, 80 for Hyper Beam and Giga Impact, 122 for Present, 123 for Frustration... It represent the move additional effects so it is indeed almost move-specific. If you want Splash to have the effect of Powder, that's what you have to change ^^

**Comment by Tyulis** [comment]
I updated my initial comment with the Z-move effect.

To dig into that I made some HUGE text files with all data, it it can help someone...

(Move flags)[https://pastebin.com/Sew7DmYq]
(Move data)[https://pastebin.com/wgni6mQ3]

**Comment by ewormPL** [comment]
Indeed, the effect field is really... specific. I was hoping I could mix some moves' effect - for example make a move that inflicts sleep on all Pokémon that share the user's type(s) (Synchronoise + sleep), but as Synchronoise has its own effect number and sleep-inducing moves also have their own, it seems impossible... In fact most of my ideas seem to be impossible to realise, that's a shame.

But all my looking seems to prove that the categories like "biting move" or "dancing move" or "Mega Launcher-boosted move" or "Bulletproof-stopped move" etc must actually not exist. The Abilities like Strong Jaw or Dancer simply are coded to react with moves of certain ID numbers. Still not sure what determines whether a move is a sound move or not. Sing doesn't seem particularly different from, say, Lovely Kiss, but one will bypass Substitute and get affected by Throat Chop or Liquid Voice - and the other won't...

**Comment by kwsch** [comment]
Disassembly indicates the game can fetch parameters by passing a 'parameter ID'.
For fetching the z move ID that a move has, you'd pass the current move ID and '32', and receive back the z-move ID which is a u16 stored at 0x1E.

![image](https://user-images.githubusercontent.com/6393368/44440213-fda7e780-a57b-11e8-9241-6a4fd60dfff1.png)

![image](https://user-images.githubusercontent.com/6393368/44440156-cb968580-a57b-11e8-9bf9-e6a956b1bb79.png)

I'm not sure what the percent and 0-4 values are used for, but a wild guess would be for Pokemon Refresh / Pelago Stats (ie, dirt or stats that get set to the pkm data as a side effect?)

**Comment by kwsch** [comment]
With https://github.com/kwsch/pk3DS/commit/dcae5d5da0a5aabb9b1b3b471e8babc58cc98a91 I've added more info to the Table Export.

**Comment by ewormPL** [comment]
Hm hm hm. The exported table now has more info indeed, namely the columns "Z3", "ZPercent" and "Flags". These flags are different than the ones pk3DS shows in the move editor. They're way more interesting.

For now, I've managed to figure out the following:
F03 = recharge turn after using (which is also effect #80)
F08 = punching move (Iron Fist)
F09 = sound move (Soundproof/Liquid Voice)
F10 = Splash
F11 = thaws user if frozen
F13 = heals (HP-recovery moves, draining moves, Heal Pulse, Wish, all that)
F14 = bypasses Substitutes (all F09 and more)
F17 = dance move (Dancer)

Moves affected by Mega Launcher, Bulletproof or Strong Jaw don't seem to have their own flags here. Most other flags seem to be very random in their move distribution, can't really tell what most of them signify.

Either way, it'd be awesome if we could actually edit these flags in pk3DS.

**Comment by Tyulis** [comment]
After a few research, values as 0x22 and 0x23 seem to be indeed Poké Refresh stats.
So at 0x22, there is the effect:

- 0 : None
- 1 : Disheveled
- 2 : Mud
- 3 : Dust
- 4 : Dry

And at 0x23 that's the probability of these effects to happen if the pokémon uses or is hit by the move. There are plenty of other parameters, but they are not related to moves.
