### ISSUE TITLE
[Feature Request] Gen7 Double battle / ect support for Trainers.

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#399]
can we get support for double battles (or triple, rotation, or 4 way battles) in S/M US/UM?

would be greatly appreciated.

**Comment by kwsch** [comment]
@dawnbomb lemme know if it doesn't work; I didn't see any double battles in either game's trainer data, but if LGPE shares structural similarity, it should be correct.

If it doesn't work, it'd be because the battle setup method the game uses is forced to singles only (doubtful). Hopefully it works :)
