### ISSUE TITLE
[Feature Request] Expand TM list

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#403]
Allow us to expand the ingame TM list to 200, 255, or higher. we can sell the new TMs at pokemarts, or have them be found with the pickup ability, or be trainer defeat rewards / ect.

**Comment by kwsch** [comment]
Sure, let me know when you get a proof of concept that works for all patches so that the changes required can be automated as an editor.

If you're not willing to figure out how to do this without pk3DS doing absolutely everything for you, then this will never happen. Please educate yourself regarding the current limits of hacking, and how to estimate the amount of time and skill required to do things that haven't been done.
