### ISSUE TITLE
Mega Evolution broken

### ISSUE THREAD

**Issue by Chosoko** [kwsch/pk3DS#420]
Everytime I enter a battle and the trainer has a potentional mega, (s)he will mega evolve. And everytime I take that Pokémon out, I get stuck in the battle. I can still use my moves, but there's no opposing Pokémon to hit. This completely ruins my game.

Only in Sun/Moon and Ultra Sun/Moon

**Comment by kwsch** [comment]
Restore backup for the trainers, and re-randomize one time only. Multiple randomizations can make things weird.

**Comment by pkmnfrk** [comment]
I don't think this is a result of multiple randomizations. I just hit this bug in Ultra Sun, and it's caused by the Mega Evolution's base HP being lower than the base form. Eg, if Latias has a base HP of 112 and Mega Latios has a base HP of 80, then the game gets really confused when it reverts the stats at the end of the battle. It goes "oh, this pokemon has HP left" and continues the battle, but the pokemon is already fainted.

(My suspicion is that this would only be an issue if the Mega was not on field at the time, but I didn't have a way to test this. I might artificially test this later, but it doesn't _really_ matter)

I tested randomizing stats from a clean state, and got the above Latias
