### ISSUE TITLE
O-Powers efficacy modification are not conserved

### ISSUE THREAD

**Issue by Rayqo** [kwsch/pk3DS#424]
When I change the efficacy of O-Powers, the new value is not registred.

**Comment by kwsch** [comment]
Offending line:
https://github.com/kwsch/pk3DS/blob/5faeb58378b562c6121f6cbe356767ae28f6838c/pk3DS/Subforms/Gen6/OPower.cs#L109

Should be replaced with:
```csharp
BitConverter.GetBytes(efficacy).CopyTo(powerData[entry], 0x12);
```

**Comment by kwsch** [comment]
Fixed via https://github.com/kwsch/pk3DS/commit/86c8cb9ba5b6665a8d1a9868508cc855d79e2809

**Comment by Rayqo** [comment]
Thanks a lot !

I have a question : Is it possible to edit the probability to trigger an encounter in a specific area ?

**Comment by kwsch** [comment]
Nah, they're hardcoded for all areas in gen6/7 iirc; changing the game code (exefs). Not really worthwhile.

**Comment by Rayqo** [comment]
And it's possible to know the encounter threshold of each area ? It would be very interesting about rng abuse (mostly on ORAS).

**Comment by kwsch** [comment]
Most just use Sweet Scent to trigger an encounter, instead of relying on the *area encounter rate*.

If I recall correctly, the area stores the encounter rates (one for grass, one for water, etc) before the encounter slots themselves (species, level, form). It's been a few years so I don't remember exactly what offset.

I'm not gonna make it editable/visible in the editor; the program serves its intended function. A lot of things need to be rewritten to a structure/class-oriented setup like pkNX/PKHeX have, rather than raw byte manipulation. Too much effort for me to do :)

**Comment by Rayqo** [comment]
In Gen 6 games, Sweet Scent trigger a horde battle. That's why wild rng abuse is complicated.
In any case, thank you to have answered my questions.
