### ISSUE TITLE
Garc Tool issues

### ISSUE THREAD

**Issue by Majickhat55** [kwsch/pk3DS#95]
The tool works fine for unpacking but refuses to repack the same garc it JUST unpacked so it makes no sense to me. It gets to 99% and just crashes the program and doesn't show any errors. It's a general "this program has stopped working". I have tried it many times, even with a fresh garc it does the same thing sans edits.  I'm on Windows 7HP x64 and the garc is a little over 1.2Gb. Any ideas?

EDIT: Forgot to mention, it doesn't even try to create a new garc. Nothing shows up while it's "packing" and the original garc's creation time doesn't change to reflect it building. If I delete the garc, nothing is created at all.

**Comment by kwsch** [comment]
Probably OutOfMemoryException, you'd have to explicitly compile the program in 64 bit mode so that it can pack with more than 2GB of RAM at its disposal.

The repacking was recently 'improved' for memory-stored GARCs (used by subforms), but the method that packs manually unpacked files has not been updated. I eventually need to simplify logic...
